name: Rust Test to DejaGnu -- Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Cargo Build, Test, Clippy, Fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Cargo Build
        run: cargo build --verbose

      - name: Cargo Test
        run: cargo test --verbose

      - name: Add rustup components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Cargo fmt
        run: cargo fmt --all --check

      - name: Clippy check
        run: cargo clippy --all-targets --all-features
